### ISSUE TITLE
the hosted service returns error 503

### ISSUE THREAD

**Issue by antoinetavant** [voelkerb/annoticity#1]
I'm trying to access the hosted service on https://earth.informatik.uni-freiburg.de/annoticity/ 

It returns an error '503 Service Unavailable' 

Is there another hosted service to try it ?

**Comment by voelkerb** [comment]
Hey, unfortunately the university servers were shut down recently. I am currently on holidays but I will let you know when I have moved the website to a new host.
Cheers,
Ben

**Comment by antoinetavant** [comment]
Thanks a lot for your quick answer, enjoy your holidays !

**Comment by voelkerb** [comment]
Try here: [http://voelkerb.com:8000](http://voelkerb.com:8000)

**Comment by aperiodicchain** [comment]
Hi @voelkerb, 
it seems http://voelkerb.com:8000 is also refusing to connect, did you move the demo? Would love to try it

**Comment by voelkerb** [comment]
Will try to host it again on the weekend

**Comment by voelkerb** [comment]
Hey @aperiodicchain 
The demo should be up and running again.
Try with [https://voelkerb.com:8000](https://voelkerb.com:8000)
