### ISSUE TITLE
It seems that there is a missing file in annoticity.

### ISSUE THREAD

**Issue by 8Jimmy** [voelkerb/annoticity#2]
I really appreciate your effort of designing Annoticiy. I am using Annoticity to label REDD. However, the following error raised:

  File "C:\Users\ASUS\anaconda3\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ASUS\Desktop\annoticity-master (2)\anno\redd.py", line 38, in getTimes
    availability = redd.loadAvailability()
  File "C:\Users\ASUS\Desktop\annoticity-master (2)\anno\datasets\REDD\reddLoader.py", line 266, in loadAvailability
    with open(path) as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'anno/datasets/REDD\\availability.json'
It means that a file called availability.json missed.

Could you do me a favor to upload availability?

**Comment by 8Jimmy** [comment]
![image](https://github.com/voelkerb/annoticity/assets/97609508/b03a48ca-8f2f-4920-ae04-74a5f88342fb)
The json file should have in this directory

**Comment by voelkerb** [comment]
Sure thing - here you go: 
[availability.json](https://github.com/voelkerb/annoticity/files/13368119/availability.json)

**Comment by voelkerb** [comment]
You could also label it [here](https://voelkerb.com:8000/anno/).
